# Generated by Django 4.1.6 on 2023-03-03 20:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.URLField(validators=[django.core.validators.URLValidator])),
                ('display_name', models.CharField(max_length=100)),
                ('github', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
                ('profile_image', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('source', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
                ('origin', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
                ('description', models.CharField(max_length=1000)),
                ('content_type', models.CharField(choices=[('text/plain', 'Text'), ('text/markdown', 'Md'), ('image/png;base64', 'Png'), ('image/jpeg;base64', 'Jpg'), ('application/base64', 'App')], max_length=50)),
                ('content', models.CharField(max_length=10000)),
                ('categories', models.CharField(max_length=1000)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends')], max_length=50)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickcomm.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickcomm.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickcomm.post')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickcomm.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickcomm.post')),
            ],
        ),
        migrations.CreateModel(
            name='follow_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='quickcomm.author')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='quickcomm.author')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='quickcomm.author')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='quickcomm.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('content_type', models.CharField(choices=[('text/plain', 'Text'), ('text/markdown', 'Md')], max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickcomm.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickcomm.post')),
            ],
        ),
    ]
